GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0NzcwNzc2M30.k5xcV8I1l9XMd4mlOnVqxb52bGvXBYXgD7Q-ydcOziY

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}


