version: '3'
services:
  api:
    container_name: api-container
    restart: always
    build: ./api
    ports:
      - "5000:5000"
  client:
    container_name: client-container
    restart: always
    build: ./my-app
    ports:
      - "3000:3000"
    depends_on:
      - api
